-- Lightweight scheduled snapshots for finance reconciliation health.
-- Purpose: keep a periodic record of the shared canonical-vs-operational
-- summary so drift can be detected even when nobody opens the admin page.

create extension if not exists pg_cron;

create table if not exists public.finance_reconciliation_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_at timestamptz not null default timezone('utc', now()),
  campus_id uuid null references public.campuses(id) on delete cascade,
  capture_mode text not null default 'scheduled',
  canonical_pending_balance numeric not null default 0,
  canonical_enrollments_with_balance bigint not null default 0,
  pending_rpc_balance numeric not null default 0,
  pending_rpc_enrollments bigint not null default 0,
  dashboard_pending_balance numeric not null default 0,
  dashboard_enrollments_with_balance bigint not null default 0,
  pending_vs_canonical_balance_drift numeric not null default 0,
  dashboard_vs_canonical_balance_drift numeric not null default 0,
  pending_vs_canonical_count_drift bigint not null default 0,
  dashboard_vs_canonical_count_drift bigint not null default 0,
  balance_drift_enrollment_count bigint not null default 0,
  constraint finance_reconciliation_snapshots_capture_mode_check
    check (capture_mode in ('scheduled', 'manual'))
);

create index if not exists finance_reconciliation_snapshots_scope_idx
  on public.finance_reconciliation_snapshots (campus_id, snapshot_at desc);

create index if not exists finance_reconciliation_snapshots_global_idx
  on public.finance_reconciliation_snapshots (snapshot_at desc)
  where campus_id is null;

create or replace function public.capture_finance_reconciliation_snapshot(
  p_campus_id uuid default null,
  p_capture_mode text default 'scheduled'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_summary record;
  v_balance_drift_enrollment_count bigint := 0;
  v_snapshot_id bigint;
begin
  if p_capture_mode not in ('scheduled', 'manual') then
    raise exception 'invalid_capture_mode';
  end if;

  select *
  into v_summary
  from public.get_finance_reconciliation_summary(p_campus_id);

  select count(*)
  into v_balance_drift_enrollment_count
  from public.list_finance_reconciliation_drift(p_campus_id, 1000000);

  insert into public.finance_reconciliation_snapshots (
    snapshot_at,
    campus_id,
    capture_mode,
    canonical_pending_balance,
    canonical_enrollments_with_balance,
    pending_rpc_balance,
    pending_rpc_enrollments,
    dashboard_pending_balance,
    dashboard_enrollments_with_balance,
    pending_vs_canonical_balance_drift,
    dashboard_vs_canonical_balance_drift,
    pending_vs_canonical_count_drift,
    dashboard_vs_canonical_count_drift,
    balance_drift_enrollment_count
  )
  values (
    timezone('utc', now()),
    p_campus_id,
    p_capture_mode,
    coalesce(v_summary.canonical_pending_balance, 0),
    coalesce(v_summary.canonical_enrollments_with_balance, 0),
    coalesce(v_summary.pending_rpc_balance, 0),
    coalesce(v_summary.pending_rpc_enrollments, 0),
    coalesce(v_summary.dashboard_pending_balance, 0),
    coalesce(v_summary.dashboard_enrollments_with_balance, 0),
    coalesce(v_summary.pending_vs_canonical_balance_drift, 0),
    coalesce(v_summary.dashboard_vs_canonical_balance_drift, 0),
    coalesce(v_summary.pending_vs_canonical_count_drift, 0),
    coalesce(v_summary.dashboard_vs_canonical_count_drift, 0),
    v_balance_drift_enrollment_count
  )
  returning id into v_snapshot_id;

  return v_snapshot_id;
end;
$$;

revoke execute on function public.capture_finance_reconciliation_snapshot(uuid, text) from public;

create or replace function public.get_latest_finance_reconciliation_snapshot(
  p_campus_id uuid default null
)
returns table(
  snapshot_at timestamptz,
  campus_id uuid,
  capture_mode text,
  canonical_pending_balance numeric,
  canonical_enrollments_with_balance bigint,
  pending_rpc_balance numeric,
  pending_rpc_enrollments bigint,
  dashboard_pending_balance numeric,
  dashboard_enrollments_with_balance bigint,
  pending_vs_canonical_balance_drift numeric,
  dashboard_vs_canonical_balance_drift numeric,
  pending_vs_canonical_count_drift bigint,
  dashboard_vs_canonical_count_drift bigint,
  balance_drift_enrollment_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    s.snapshot_at,
    s.campus_id,
    s.capture_mode,
    s.canonical_pending_balance,
    s.canonical_enrollments_with_balance,
    s.pending_rpc_balance,
    s.pending_rpc_enrollments,
    s.dashboard_pending_balance,
    s.dashboard_enrollments_with_balance,
    s.pending_vs_canonical_balance_drift,
    s.dashboard_vs_canonical_balance_drift,
    s.pending_vs_canonical_count_drift,
    s.dashboard_vs_canonical_count_drift,
    s.balance_drift_enrollment_count
  from public.finance_reconciliation_snapshots s
  where (
    p_campus_id is null and s.campus_id is null
  ) or s.campus_id = p_campus_id
  order by s.snapshot_at desc
  limit 1;
$$;

grant execute on function public.get_latest_finance_reconciliation_snapshot(uuid) to authenticated;

select public.capture_finance_reconciliation_snapshot(null, 'manual');

do $$
begin
  perform cron.unschedule('capture-finance-reconciliation-snapshot');
exception when others then
  null;
end $$;

select cron.schedule(
  'capture-finance-reconciliation-snapshot',
  '15 */6 * * *',
  $cron$select public.capture_finance_reconciliation_snapshot(null, 'scheduled')$cron$
);
